name: Block Suggestion
description: Create a block suggestion to help expand the blocks Architecture Extensions has to offer.
labels: [suggestion]
body:
  - type: markdown
    attributes:
      value: "## Welcome!"
  - type: markdown
    attributes:
      value: |
        Thanks for taking your time to create your block suggestion! If you want to discuss your suggestion, join us on Discord.
        Make sure you are running the latest version of Architecture Extensions before making the suggestion.
  - type: textarea
    id: block-list
    attributes:
      label: List the blocks you want added to Arch-Ex.
      description: If you are suggesting new blocktype(s), go to the next input field.
      value: |
        - Cobblestone columns

  - type: textarea
    id: new-blocktype
    attributes:
      label: List the blocktype(s) you want added to Arch-Ex.
      description: This is where you'd put your blocktypes you want added to Arch-Ex if applicable.
      value: |
        - Crown Moldings

  - type: textarea
    id: blocktypes
    attributes:
      label: What blocktypes do your block(s) fall under if applicable.
      description: Your block can fall under multiple block types if applicable.
      value: |
        - Column, Molding, Beam

  - type: textarea
    id: description
    attributes:
      label: Describe how your blocktype(s) will work if applicable.
      description: "Describe the suggestion as clearly as possible. More info means the suggestion is more likely to be accepted."
      value: |
        The crown molding blocks can be placed on ceilings to add extra detail to a space.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "Add any other context about the block suggestion here."
